name: Publish

#on:
#  push:
#    branches:
#      - main

on: [push, pull_request]

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Checkout client
        uses: actions/checkout@v3
        with:
          repository: FLock-io/client
          token: ${{ secrets.GH_TOKEN }}
          ref: 'main'
          path: './client'

      - name: Import Cert
        if: runner.os == 'macOS'
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Build main client
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: ./client/main.py

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        run: |
          npm install --force
          npm run postinstall
          npm run build

      - name: Move main.bin
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: |
          mv ./build/main.bin ./build/bin/main.bin

      - name: Move main.exe
        if: runner.os == 'Windows'
        run: |
          mv ./build/main.exe ./build/bin/main.exe

      - name: Sign main executable
        if: runner.os == 'macOS'
        run: |
          codesign --deep --options runtime --timestamp --force --verify --verbose --sign "Developer ID Application: FLock.io LTD (35H5QAYP2F)" build/bin/main.bin

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always
